"""empty message

Revision ID: be42ebcf5759
Revises: 2cad17da203a
Create Date: 2022-01-19 20:47:16.126799

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'be42ebcf5759'
down_revision = '2cad17da203a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('todo', 'body')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todo', sa.Column('body', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
